enum GlobalSettingOption {
  FOLLOW_CIN_FILE,
  YES,
  NO,
}

const GLOBAL_SETTING_OPTION_DESC: string[] = ["由CIN檔案指定", "是", "否"];

const GLOBAL_SETTING_SPACE_STYLE_DESC: string[] = [
  "由CIN檔案指定",
  "按空白立即送出第一字(嘸蝦米、大易)",
  "按滿按空白送出第一字",
  "",
  "按滿按空白不送出第一字(倉頡、行列)",
];

const DEFAULT_GLOBAL_SETTING_OPTION = GlobalSettingOption.FOLLOW_CIN_FILE;

const GLOBAL_SETTING_FLAG_DISP_PARTIAL_MATCH: string =
  "GLOBAL_SETTING.FLAG_DISP_PARTIAL_MATCH";
const GLOBAL_SETTING_FLAG_DISP_FULL_MATCH: string =
  "GLOBAL_SETTING.FLAG_DISP_FULL_MATCH";
const GLOBAL_SETTING_FLAG_VERTICAL_SELECTION: string =
  "GLOBAL_SETTING.FLAG_VERTICAL_SELECTION";
const GLOBAL_SETTING_SPACE_STYLE: string = "GLOBAL_SETTING.SPACE_STYLE";

const TITLE_GLOBAL_SETTING: {
  [index: string]: string;
} = {};
TITLE_GLOBAL_SETTING[GLOBAL_SETTING_FLAG_DISP_PARTIAL_MATCH] =
  "預選列中顯示部份符合的字";
TITLE_GLOBAL_SETTING[GLOBAL_SETTING_FLAG_DISP_FULL_MATCH] = "預覽/預選字";
TITLE_GLOBAL_SETTING[GLOBAL_SETTING_FLAG_VERTICAL_SELECTION] = "垂直選擇";
TITLE_GLOBAL_SETTING[GLOBAL_SETTING_SPACE_STYLE] = "空白鍵選項";

function initDefaultGlobalSettings() {
  [
    GLOBAL_SETTING_FLAG_DISP_PARTIAL_MATCH,
    GLOBAL_SETTING_FLAG_DISP_FULL_MATCH,
    GLOBAL_SETTING_FLAG_VERTICAL_SELECTION,
    GLOBAL_SETTING_SPACE_STYLE,
  ].map((v: string) => {
    if (localStorage.getItem(v) === null) {
      localStorage.setItem(v, String(DEFAULT_GLOBAL_SETTING_OPTION));
    }
  });
}

export {
  initDefaultGlobalSettings,
  GlobalSettingOption,
  GLOBAL_SETTING_OPTION_DESC,
  GLOBAL_SETTING_SPACE_STYLE_DESC,
  DEFAULT_GLOBAL_SETTING_OPTION,
  GLOBAL_SETTING_FLAG_DISP_PARTIAL_MATCH,
  GLOBAL_SETTING_FLAG_DISP_FULL_MATCH,
  GLOBAL_SETTING_FLAG_VERTICAL_SELECTION,
  GLOBAL_SETTING_SPACE_STYLE,
  TITLE_GLOBAL_SETTING,
};
